// Code generated by Soft build; DO NOT EDIT.
package soft

func NewSoft() *Soft {
	s := &Soft{
		Name:      "版本控制-软件",
		Alias:     "别名",
		Author:    "作者",
		Copyright: "All rights reserved",
		Version: Version{
			Version:   "0.0.1",
			Status:    Base,
			GitHash:   "1f10cb1d57ef6e1ce962634148c95223bd2e4d0f",
			updatedAt: "2020.06.15 17:12:44",
			Log:       "init",
		},
		Inherit: true,
	}
	return s
}
