// Code generated by Soft build; DO NOT EDIT.
package soft

func NewSoft() *Soft {
	s :=
		&Soft{
			Name:      "xx-软件",
			Alias:     "别名",
			Author:    "作者",
			Copyright: "All rights reserved",
			Version: []Version{
				{
					Version:   "0.0.1",
					Status:    Base,
					GitHash:   "",
					CreatedAt: "2020.08.03 18:27:20",
					Log:       "init",
				},
			},
		}
	return s
}
